---
title: 'Week 3 DS Recitation Part 1'
date: "`r format(Sys.time(), '%d %B, %Y')`"
author: "SIBDS 2024 @ Columbia"
output: pdf_document
---

## Getting Started

### Tasks:

1. Create a new R project and named it `Week 3 DS Recitation`

2. Put the `week_3_DS_recitation.Rmd` file into the same folder of the R project you just created. 

3. Modify the YAML header as follows:

```
---
title: "Week 3 DS Recitation"
date: "`r format(Sys.time(), '%d %B, %Y')`"
author: "SIBDS 2024 @ Columbia" 
output: 
  html_document:
    toc: true
    code_folding: "show"
---
```

   Now, knit this `.Rmd` file to make sure it runs as expected.

4. Finally, create a folder within the project folder named `data`. 

## Writing with Data

### Tasks:

  1. Write a named code chunk names `sample_df` that creates a dataframe comprised of
  
      * `random_vec` : A `numeric` variable containing a random sample of size `500` from a normal variable with mean `1` and standard deviation `3`.
    
      * `logical_vec` : A `logical` vector indicating whether each sampled value is greater than zero, can you do it in the simplest way?
    
      * `abs_vec`: A `numeric` vector containing the absolute value (using `abs()`) of each element. 
  

  
  2. Produce a histogram of the absolute value variable just created.
  


  3. Fill in the blank using the in-line code giving the mean, median, and standard deviation of `random_vec` (*Hint*: you may need to use the `pull()` function in `tidyverse`):
  
      * Mean: REPLACE THIS BY YOUR CODE
  
      * Median: REPLACE THIS BY YOUR CODE   
  
      * SD: REPLACE THIS BY YOUR CODE

  